apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      hostAliases:
        - ip: "10.96.0.88"
          hostnames:
            - "aloco.local"
      containers:
        - name: web
          image: dormammun/looport-web:latest
          env:
            - name: NEXT_PUBLIC_API_HOST
              value: {{.Values.app.host}}
            - name: NEXT_PUBLIC_ENV
              value: {{.Values.app.env}}
---
apiVersion: v1
kind: Service
metadata:
  name: web-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
{{- if .Values.app.env | eq "development" }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-debug-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: web-debug
      protocol: TCP
      port: 9204
      targetPort: 9229
{{- end }}