apiVersion: skaffold/v4beta6
kind: Config
deploy:
  helm:
    releases:
      - name: aloco
        skipBuildDependencies: true
        chartPath: ./template
        valuesFiles:
          - ./template/values-development.yaml
build:
  local:
    concurrency: 3
  artifacts:
    - image: dormammun/looport-passport
      docker:
        dockerfile: infrastructure/images/passport/Dockerfile
      context: ../../
    - image: dormammun/looport-telegraph
      docker:
        dockerfile: infrastructure/images/telegraph/Dockerfile
      context: ../../
    - image: dormammun/looport-web
      docker:
        dockerfile: infrastructure/images/web/Dockerfile
      context: ../../