apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: nats
  template:
    metadata:
      labels:
        provider: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10.1-alpine3.18
          args:
            [
              '-p',
              '4222',
              '-m',
              '8222'
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-cluster-ip
spec:
  type: ClusterIP
  selector:
    provider: nats
  ports:
    - name: nats-client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: nats-monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
{{ if eq .Values.app.env "development" }}
---
apiVersion: v1
kind: Service
metadata:
  name: nats-load-balancer
spec:
  type: LoadBalancer
  selector:
    provider: nats
  ports:
    - name: nats-client-debug
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: nats-monitoring-debug
      protocol: TCP
      port: 8222
      targetPort: 8222
{{ end }}