apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aloco-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.host }}
      http:
        paths:
          - path: /api/passport(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: passport-cluster-ip
                port:
                  number: 3000
          - path: /api/telegraph(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: telegraph-cluster-ip
                port:
                  number: 3000
          - path: /(|)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-cluster-ip
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-cluster-ip
  namespace: ingress-nginx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: controller
  clusterIP: {{ .Values.ingress.clusterIP }}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443