import '@/ui/common/styles/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ReactNode} from 'react'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: ReactNode
  modal: ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Aloco Video Chat</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
      </head>
      <body className={inter.className}>
        {modal}
        {children}
      </body>
    </html>
  )
}
