app:
  env: development
  name: aloco
  host: aloco.local
  enableIngress: false
  jwt:
    secret: "ioj*(*jd##$"
    expires: "1d"

passport:
  name: "passport"
  pg:
    user: "root"
    password: "root"
    db: "passport"

messenger:
  name: "messenger"
  pg:
    user: "root"
    password: "root"
    db: "messenger"
