app:
  env: development
  name: aloco
  host: aloco.local
  enableIngress: false
  jwt:
    secret: "998idfj09()J%F"
    expires: "1d"

passport:
  name: "passport"
  pg:
    user: "root"
    password: "root"
    db: "passport"

telegraph:
  name: "telegraph"
  pg:
    user: "root"
    password: "root"
    db: "telegraph"
