name: Test Infrastructure
on:
  pull_request:
    paths:
      - 'infrastructure/k8s/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
      - run: cd infrastructure/k8s && sh cmd.sh lint