name: Running @looport/passport tests

on:
  pull_request:
    paths:
      - 'application/services/passport/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm -F @looport/passport install
      - run: pnpm -F @looport/passport lint
  type-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm -F @looport/passport install
      - run: pnpm -F @looport/passport type-check
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm -F @looport/passport install
      - run: pnpm -F @looport/passport test:all