name: Test @looport/telegraph

on:
  pull_request:
    paths:
      - 'application/services/telegraph/**'
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: pnpm -F @looport/telegraph install && pnpm -F @looport/telegraph^... build
      - run: pnpm -F @looport/telegraph test:all
        env:
          DB_PASSWORD: root
          DB_USER: root
          DB_NAME: db
          DB_HOST: postgres
          DB_PORT: 5432
          JWT_SECRET: 'secret'
          JWT_EXPIRES: '1d'
          NATS_URL: 'nats-url'
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: pnpm -F @looport/telegraph install && pnpm -F @looport/telegraph^... build
      - run: pnpm -F @looport/telegraph lint
  type-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: pnpm -F @looport/telegraph install && pnpm -F @looport/telegraph^... build
      - run: pnpm -F @looport/telegraph type-check
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: pnpm -F @looport/telegraph install && pnpm -F @looport/telegraph... build