name: Verifier e2e Test

on:
  pull_request:
    paths:
      - 'application/services/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          WEB_URL: http://aloco.local
          API_URL: http://aloco.local/api
      - uses: hiberbee/github-action-skaffold@1.20.0
        with:
          command: build
          repository: ghcr.io/hiberbee/docker
          image: nodejs
          tag: ${{ github.sha }}
      - uses: medyagh/setup-minikube@master
        with:
          kubernetes-version: 1.22.2
          memory: 4096
          cpus: 2
          driver: docker
      - run: |
            export SHELL=/bin/bash
            eval $(minikube -p minikube docker-env)
            cd infrastructure/k8s/web/images && sh cmd.sh buildx
            cd infrastructure/k8s/passport/images && sh cmd.sh buildx
            echo -n "verifying images:"
            docker images
      - uses: azure/setup-helm@v3
      - run: cd infrastructure/k8s && sh cmd.sh run-local
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: sudo echo "127.0.0.1 aloco.local" | sudo tee -a /etc/hosts
      - run: pnpm -F @looport/verifier install
      - run: pnpm -F @looport/verifier test