name: Deploy @looport/web
on:
  push:
    branches:
      - main
    paths:
      - 'application/services/web'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd infrastructure/images/web && sh buildx.sh

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_CONTEXT_ID }}
      - run: kubectl rollout restart deployment web